---
name: Test agent_crewai
on:
  push:
    branches: ["main"]
    paths:
      - 'agent_crewai/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'agent_crewai/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: agent_crewai
jobs:
  docker-build-test:
    name: "Agent: agent_crewai Docker build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v5"
      - name: Build Docker Image
        run: |
          cd docker_context
          tar -czh . | docker build - -t agent_crewai
  tests:
    name: "Agent: agent_crewai ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v5"
      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev
      - name: Run Static Checks
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy --pretty .
      - name: Test
        run: uv run pytest --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: agent_crewai/.coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
